config/routes.rb
PMDB3::Application.routes.draw do
  resources :tags

  resources :agroups

  get 'attris/search' => 'attris#search'
  post 'attris/find' => 'attris#find', as: 'find_attris'
  resources :attris do
    get 'autocomplete', :on => :collection
  end

  resources :folders

  resources :media_objects do
    post 'add_attri', :on => :member
    delete 'remove_attri', :on => :member
    get 'edit2', :on => :member
    get 'new_tag', :on => :member
    get 'update_tag', :on => :member
    get 'delete_tag', :on => :member
    get 'pic', :on => :member
  end

  resources :storage_locations do
    put 'set', :on => :member
    put 'scan_directory', :on => :member
    put 'scan_files', :on => :member
    
  end

  resources :locations do
    post 'upd_and_check', :on => :member
  end

  resources :storages

end

app/models/storage_location.rb
class StorageLocation < ActiveRecord::Base
  validates :storage_id, presence: true
  validates :filePath_id, presence: true
  validates :webPath_id, presence: true
  validates :tnFilePath_id, presence: true
  validates :tnWebPath_id, presence: true
  
  belongs_to :storage
  belongs_to :filePath, class_name: "Location"
  belongs_to :webPath,  class_name: "Location"
  belongs_to :tnFilePath, class_name: "Location"
  belongs_to :tnWebPath, class_name: "Location"

end

app/controllers/storage_locations_controller.rb
class StorageLocationsController < ApplicationController
  
  # GET /storage_locations
  # GET /storage_locations.json
  def index
    @storage_locations = StorageLocation.order(:storage_id).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @storage_locations }
    end
  end

  # GET /storage_locations/1
  # GET /storage_locations/1.json
  def show
    @storage_location = StorageLocation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @storage_location }
    end
  end

  # GET /storage_locations/new
  # GET /storage_locations/new.json
  def new
    @storage_location = StorageLocation.new
    @storage = Storage.find(params[:storage_id])
    @storage_location.storage = @storage

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @storage_location }
    end
  end

  # GET /storage_locations/1/edit
  def edit
    @storage_location = StorageLocation.find(params[:id])
  end

  # POST /storage_locations
  # POST /storage_locations.json
  def create
    @storage_location = StorageLocation.new(params[:storage_location])


    respond_to do |format|
      if @storage_location.save
        format.html { redirect_to @storage_location, notice: 'Storage location was successfully created.' }
        format.json { render json: @storage_location, status: :created, location: @storage_location }
      else
        format.html { render action: "new" }
        format.json { render json: @storage_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /storage_locations/1
  # PUT /storage_locations/1.json
  def update
    @storage_location = StorageLocation.find(params[:id])

    respond_to do |format|
      if @storage_location.update_attributes(params[:storage_location])
        format.html { redirect_to @storage_location, notice: 'Storage location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @storage_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storage_locations/1
  # DELETE /storage_locations/1.json
  def destroy
    @storage_location = StorageLocation.find(params[:id])
    @storage_location.destroy

    respond_to do |format|
      format.html { redirect_to storage_locations_url }
      format.json { head :ok }
    end
  end
  
  # Post /storage_locations/1/set
  def set
      @storage_location = StorageLocation.find(params[:id])
      @storage_location.inUse = true;
      @storage_location.save;
      
      storage_id = @storage_location.storage_id
      
      sls = StorageLocation.where("storage_id = ? AND id <> ?", storage_id, @storage_location.id)
      sls.each do |sl|
        sl.update_attributes(inUse: :false)        
      end
      redirect_to storage_locations_path, notice: 'storage gesetzt'   
  end
  
  def scan_directory
    @storage_location = StorageLocation.find(params[:id])
    @filepath = @storage_location.filePath.uri
    @storage = @storage_location.storage

    h = Help.new
    path = @filepath + "/"+ @storage.path
    @entries = []
    if File.exist?(path)
      
      @entries = h.getDirectory(path)

      @entries = @entries.map do|e|
       a = e.sub(@filepath, "").sub(@storage.path,"").gsub("//","/")       
       i = a.index(/\/[^\/]+$/)
       if i 
         lfolder = a.slice(i+1,255)
         mpath = a.slice(0,i+1)
          a = mpath +"   " + lfolder
       else 
         lfolder = ""
         mpath = a
       end
       f = Folder.where("storage_id = ? and lfolder = ? and mpath = ?",@storage.id, lfolder, mpath).first
       unless f
         f = Folder.new(storage_id: @storage.id, lfolder: lfolder, mpath: mpath)
         m = MediaObject.new(name: lfolder, typ_id: 1024)
 #        f.mediaObject = m
 #        f.save
 #        m.folder_id = f.id
  #       m.save
         m.folder = f
         m.save
         f.mediaObject_id = m.id
         f.save
       end
       a
      end
      
   end 
   @entries << path
 end

 def scan_files
    @storage_location = StorageLocation.find(params[:id])
    @filepath = @storage_location.filePath.uri
    @storage = @storage_location.storage

    h = Help.new
    path = @filepath + "/"+ @storage.path
    @entries = []
    if File.exist?(path)
      
      @entries = h.getFiles(path)

      @entries = @entries.map do|e|
       a = e.sub(@filepath, "").sub(@storage.path,"").gsub("//","/")       
       i = a.index(/\/[^\/]+$/)
       if i 
         file = a.slice(i+1,255)
         path = a.slice(0,i)
         i = path.index(/\/[^\/]+$/)
           if i
             lfolder = path.slice(i+1,255)
             mpath = path.slice(0,i+1)
           else
             lfolder = path
             mpath = "/"
           end
       else 
         adafd
         file = a
         mpath = "/"
         lfolder = ""
       end
       a = mpath +"--- " + lfolder+"----" + file
       
       f = Folder.where("storage_id = ? and lfolder = ? and mpath = ?",@storage.id, lfolder, mpath).first
       unless f
         @stp = 1
         break
       end
       a = a + "   ::  "+ f.id.to_s
        
       
#       f = Folder.new(storage_id: @storage.id, lfolder: lfolder, mpath: mpath)
       mo = MediaObject.new(name: file, typ_id: 2, folder_id: f.id).save
#       f.mediaObject = m
#       f.save
        a
      end
      if @stp 
        @entries = ["please scan folders"]
      end
   end 

   
   render 'scan_directory'
 end

end

app/helpers/storage_locations_helper.rb
module StorageLocationsHelper
end

app/views/storage_locations/_form.html.erb
<%= form_for(@storage_location) do |f| %>
  <% if @storage_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@storage_location.errors.count, "error") %> prohibited this storage_location from being saved:</h2>

      <ul>
      <% @storage_location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :storage_id %><br />
    <%= f.check_box :inUse %>
  </div>
     	
  <div class="field">
    <%= f.label :storage %><br />
    <%= link_to @storage_location.storage.name, edit_storage_path(@storage_location.storage)%>

    <%= f.hidden_field :storage_id %>
  </div
  
  <div class="field">
    <%= f.label :filePath_id %><br />
    <%= f.select :filePath_id,
    			  Location.where(usagetype: 1).map {|l| [l.name, l.id]},
    			  prompt: "Bitte wählen" %>

  </div>
  <div class="field">
    <%= f.label :webPath_id %><br />
    <%= f.select :webPath_id,
    			  Location.where(usagetype: 1).map {|l| [l.name, l.id]},
    			  prompt: "Bitte wählen"  %>
  </div>
  <div class="field">
    <%= f.label :tnFilePath_id %><br />
    <%= f.select :tnFilePath_id,
    			  Location.where(usagetype: 1).map {|l| [l.name, l.id]},
    			  prompt: "Bitte wählen"  %>
  </div>
  <div class="field">
    <%= f.label :tnWebPath_id %><br />
    <%= f.select :tnWebPath_id,
    			  Location.where(usagetype: 1).map {|l| [l.name, l.id]},
    			  prompt: "Bitte wählen" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/storage_locations/edit.html.erb
<h1>Editing storage_location</h1>

<%= render 'form' %>
<%= link_to 'Show and Scan', @storage_location %> |

app/views/storage_locations/index.html.erb
<h1>Listing storage_locations</h1>
<table>
	<tr>
		<th>In use</th>
		<th>Storage</th>
		<th>Filepath</th>
		<th>Webpath</th>
		<th>Tnfilepath</th>
		<th>Tnwebpath</th>		
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% name1 = ""
	@storage_locations.each do |storage_location| %>
	<% name = storage_location.storage.name
	     unless name == name1
	         name1 = name%>
	       <tr><td><hr></tr>
	     <%end%>
	<tr>
		<td><%= storage_location.inUse%> <%= link_to 'Set', set_storage_location_path(storage_location), method: :put %></td>
		<td><%= storage_location.storage.name %></td>
		<td><%= storage_location.filePath.name %></td>
		<td><%= storage_location.webPath.name %></td>
		<td><%= storage_location.tnFilePath.name%></td>
		<td><%= storage_location.tnWebPath.name %></td>
		<td><%= link_to 'Show', storage_location %></td>
		<td><%= link_to 'Edit', edit_storage_location_path(storage_location) %></td>
		<td><%= link_to 'Destroy', storage_location, confirm: 'Are you sure?', method: :delete %></td>
	</tr>
	<% end %>
</table>
<br />

app/views/storage_locations/new.html.erb
<h1>New storage_location</h1>

<%= render 'form' %>

<%= link_to 'Back', storage_locations_path %>

app/views/storage_locations/scan_directory.html.erb
<table>
	<% @entries.each do |entry| %>
	<tr>
		<td><%= entry %></td>

	</tr>
	<% end %>
</table>

app/views/storage_locations/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>

	<b>Storage:</b>
	<%= @storage_location.storage.name %>
</p>

<table>
	<th>

	<tr>
		<td>Pfadtyp</td>
		<td>Pfad</td>
		<td>Storage Pfad</td>
	<tr>
		<td>Filepath</td>
		<td> <%= @storage_location.filePath.name %> </td>
		<td>
		<%= link_to @storage_location.filePath.uri, location_path(@storage_location.filePath_id)%>
       </td>
       <td>/</td>
       <td><%=@storage_location.storage.path%></td>
	</tr>
	<tr>
		<td> Webpath <td> <%= @storage_location.webPath.name %>
	</tr>
	<tr>
		<td>Tnfilepath <td><%= @storage_location.tnFilePath.name %>
	</tr>
	<tr>

		<td>Inuse</td>
		<td><%= @storage_location.inUse %></td>
	</tr>

</table>

<%= link_to "Scan Directory", scan_directory_storage_location_path(@storage_location), method: :put%>
<%= link_to "Scan and add Files", scan_files_storage_location_path(@storage_location), method: :put%>


<%= link_to 'Edit', edit_storage_location_path(@storage_location) %> |
<%= link_to 'Back', storage_locations_path %>