config/routes.rb
PMDB3::Application.routes.draw do
  resources :tags

  resources :agroups

  get 'attris/search' => 'attris#search'
  post 'attris/find' => 'attris#find', as: 'find_attris'
  resources :attris do
    get 'autocomplete', :on => :collection
  end

  resources :folders

  resources :media_objects do
    post 'add_attri', :on => :member
    delete 'remove_attri', :on => :member
    get 'edit2', :on => :member
    get 'new_tag', :on => :member
    get 'update_tag', :on => :member
    get 'delete_tag', :on => :member
    get 'pic', :on => :member
  end

  resources :storage_locations do
    put 'set', :on => :member
    put 'scan_directory', :on => :member
    put 'scan_files', :on => :member
    
  end

  resources :locations do
    post 'upd_and_check', :on => :member
  end

  resources :storages

end

app/models/storage.rb
class Storage < ActiveRecord::Base
    has_many :storageLocations, dependent: :destroy
    has_many :folders, dependent: :destroy
  
  def filePath
    getSl.filePath.uri+"/"+path
  end

  def webPath
    getSl.webPath.name
  end

  def tnFilePath
    getSl.tnFilePath.name
  end

  def tnWebPath
    getSl.tnWebPath.name
  end

  private

  def getSl
    @sl ||= StorageLocation.where("storage_id = ? AND inUse = ?", id, true).first
  end

end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  # GET /storages
  # GET /storages.json
  def index
    @storages = Storage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @storages }
    end
  end

  # GET /storages/1
  # GET /storages/1.json
  def show
    @storage = Storage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @storage }
    end
  end

  # GET /storages/new
  # GET /storages/new.json
  def new
    @storage = Storage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @storage }
    end
  end

  # GET /storages/1/edit
  def edit
    @storage = Storage.find(params[:id])
  end

  # POST /storages
  # POST /storages.json
  def create
    @storage = Storage.new(params[:storage])

    respond_to do |format|
      if @storage.save
        format.html { redirect_to @storage, notice: 'Storage was successfully created.' }
        format.json { render json: @storage, status: :created, location: @storage }
      else
        format.html { render action: "new" }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /storages/1
  # PUT /storages/1.json
  def update
    @storage = Storage.find(params[:id])

    respond_to do |format|
      if @storage.update_attributes(params[:storage])
        format.html { redirect_to @storage, notice: 'Storage was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1
  # DELETE /storages/1.json
  def destroy
    @storage = Storage.find(params[:id])
    @storage.destroy

    respond_to do |format|
      format.html { redirect_to storages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/storages/_form.html.erb
<%= form_for(@storage) do |f| %>
  <% if @storage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@storage.errors.count, "error") %> prohibited this storage from being saved:</h2>

      <ul>
      <% @storage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/storages/edit.html.erb
<h1>Editing storage</h1>

<%= render 'form' %>

 <%@storage_locations = @storage.storageLocations%>
<table>
	<tr>
		<th>In use</th>
		<th>Storage</th>
		<th>Filepath</th>
		<th>Webpath</th>
		<th>Tnfilepath</th>
		<th>Tnwebpath</th>		
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% @storage_locations.each do |storage_location| %>
	<tr>
		<td><%= storage_location.inUse%> <%= link_to 'Set', set_storage_location_path(storage_location), method: :put %></td>
		<td><%= storage_location.storage.name %></td>
		<td><%= storage_location.filePath.name %></td>
		<td><%= storage_location.webPath.name %></td>
		<td><%= storage_location.tnFilePath.name%></td>
		<td><%= storage_location.tnWebPath.name %></td>
		<td><%= link_to 'Show', storage_location %></td>
		<td><%= link_to 'Edit', edit_storage_location_path(storage_location) %></td>
		<td><%= link_to 'Destroy', storage_location, confirm: 'Are you sure?', method: :delete %></td>
	</tr>
	<% end %>
</table>

<%= link_to 'Back', storages_path %>|
<%= link_to 'New Storage Location', new_storage_location_path+"?storage_id="+@storage.id.to_s%>
<p></p>
<%= link_to 'Folders', folders_path+"?storage_id="+@storage.id.to_s%>

app/views/storages/index.html.erb
<h1>Listing storages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @storages.each do |storage| %>
  <tr>
    <td><%= storage.name %></td>
    <td><%= storage.path %></td>
    <td><%= link_to 'Show', storage %></td>
    <td><%= link_to 'Edit', edit_storage_path(storage) %></td>
    <td><%= link_to 'Destroy', storage, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Storage', new_storage_path %>

app/views/storages/new.html.erb
<h1>New storage</h1>

<%= render 'form' %>

<%= link_to 'Back', storages_path %>

app/views/storages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @storage.name %>
</p>

<p>
  <b>Path:</b>
  <%= @storage.path %>
</p>


<%= link_to 'Edit', edit_storage_path(@storage) %> |
<%= link_to 'Back', storages_path %>