config/routes.rb
PMDB3::Application.routes.draw do
  resources :tags

  resources :agroups

  get 'attris/search' => 'attris#search'
  post 'attris/find' => 'attris#find', as: 'find_attris'
  resources :attris do
    get 'autocomplete', :on => :collection
  end

  resources :folders

  resources :media_objects do
    post 'add_attri', :on => :member
    delete 'remove_attri', :on => :member
    get 'edit2', :on => :member
    get 'new_tag', :on => :member
    get 'update_tag', :on => :member
    get 'delete_tag', :on => :member
    get 'pic', :on => :member
  end

  resources :storage_locations do
    put 'set', :on => :member
    put 'scan_directory', :on => :member
    put 'scan_files', :on => :member
    
  end

  resources :locations do
    post 'upd_and_check', :on => :member
  end

  resources :storages

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :mediaObject, dependent: :destroy
  has_many :storageLocations
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new(params[:location])
    @location.usagetype = params[:ut]
    #location.href = "http://127.0.0.1/locations/new?location[uri]="+location.href

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
    h = Help.new
    @media_object = h.get_media_object(@location, "bookmark")
    @tag = h.get_tag(@media_object)

  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    ## Handling von verbundenen Objekten
    h = Help.new
    @media_object=h.new_media_object(@location, "bookmark")
    #    view_context.new_tag(@media_object)  // funktioniert
    @tag = h.new_tag(@media_object, params[:location][:name], nil)

    if @location.usagetype == 99
      @target = @location.uri
    else
      @target = @location
    end

    respond_to do |format|
      if @location.save
        #      @location.mediaObject =  @media_object
        format.html { redirect_to @target , notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :ok }
    end
  end

  def upd_and_check
    @location = Location.find(params[:id])
    @media_object = @location.mediaObject

 #   if @location.update_attributes(params[:location])
      if File.exist?(@location.uri)
        @directoryOK = "Exists"
      end
      render action: "edit"
  #  else
   #   format.html { render action: "edit" }
  #    format.json { render json: @location.errors, status: :unprocessable_entity }
  #  end
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_assign_attris.html.erb
<div class='attri'>
	<table>
		<tr>
			<th>Name</th>
			<th>Agroup</th>
			<th>Id sort</th>
			<th>Parent</th>
			<th>Keycode</th>
			<th>Group</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
		<% @attris = @location.mediaObject.attris
		@attris.each do |attri| %>
		<tr>
			<td><%= attri.name %></td>
			<td><%= attri.agroup_id %></td>
			<td><%= attri.id_sort %></td>
			<td><%= attri.parent_id %></td>
			<td><%= attri.keycode %></td>
			<td><%= attri.group_id%></td>
			<td><%= link_to 'Show', attri %></td>
			<td><%= link_to 'Edit', edit_attri_path(attri) %></td>
			<td><%= link_to 'Destroy', remove_attri_media_object_path(@location.mediaObject)+"?attri_id="+attri.id.to_s, confirm: 'Are you sure?', method: :delete%></td>
		</tr>
		<% end %>
	</table>
	<%= form_tag add_attri_media_object_path(@location.mediaObject), remote: true do%>
	<%= text_field_tag :name, ""%>
	<%= submit_tag "ADD"%>
	<% end%>
</div>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, size: 100%>
  </div>
  <div class="field">
    <%= f.label :uri %><br />
    <%= f.text_field :uri, size: 100%>

    <%=link_to("Check", upd_and_check_location_path(@location.id||1), method: :post) if @location.id%>
    <%= @directoryOK%>
  </div>
  <div class="field">
    <%= f.label :usagetype %><br />
    <%= f.number_field :usagetype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= render :partial => 'shared/assign_attris' %>
<%= render :partial => 'shared/edit_tag' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Name</th>

    <th>Usagetype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.mediaObject_id %></td>
    <td><%= link_to location.name , location.uri %></td>
    <td><%= location.usagetype %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Uri:</b>
  <%= @location.uri %>
</p>

<p>
  <b>Description:</b>
  <%= @location.description %>
</p>

<p>
  <b>Usagetype:</b>
  <%= @location.usagetype %>
  <%= @location.mediaObject.id%>
  <%= @location.mediaObject.location%>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>