config/routes.rb
PMDB3::Application.routes.draw do
  resources :tags

  resources :agroups

  get 'attris/search' => 'attris#search'
  post 'attris/find' => 'attris#find', as: 'find_attris'
  resources :attris do
    get 'autocomplete', :on => :collection
  end

  resources :folders

  resources :media_objects do
    post 'add_attri', :on => :member
    delete 'remove_attri', :on => :member
    get 'edit2', :on => :member
    get 'new_tag', :on => :member
    get 'update_tag', :on => :member
    get 'delete_tag', :on => :member
    get 'pic', :on => :member
  end

  resources :storage_locations do
    put 'set', :on => :member
    put 'scan_directory', :on => :member
    put 'scan_files', :on => :member
    
  end

  resources :locations do
    post 'upd_and_check', :on => :member
  end

  resources :storages

end

app/models/Picture.rb
class Picture < MediaObject
  
end

app/models/agroup.rb
class Agroup < ActiveRecord::Base
end

app/models/attri.rb
class Attri < ActiveRecord::Base
  has_and_belongs_to_many :mediaObjects
  belongs_to :agroup
end

app/models/attris_media_objects.rb
class AttrisMediaObjects < ActiveRecord::Base
end

app/models/bookmark.rb
class Bookmark < MediaObject
  has_one :location, foreign_key: :mediaObject_id
   has_and_belongs_to_many   :attris
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  # belongs_to :mediaObject, dependent: :destroy  # tested and okay
  has_many :mediaObjects , dependent: :destroy  # tested and okay
  
  def filePath

    storage = Storage.find(storage_id)
    a =     storage.filePath + "/" +  mpath + "/" +  lfolder 
    a.gsub("//", "/").gsub("//", "/")
  end
  
  def mediaObject # not tested yet
    MediaObject.find(mediaObject.id)
  end

end

app/models/help.rb
require 'find'

class Help
  def new_tag(mo, title, description)
    if title || description
      tag = Tag.new(title: title, description: description)
    mo.tag = tag
    end
  end

  def get_tag(mo)
    tag = mo.tag
    #       unless tag
    #     tag = Tag.new
    #     mo.tag = tag
    #   end
    tag
  end

  def new_media_object (cobject, na)
    @media_object = Bookmark.new
    @media_object.name = na

    @media_object.typ_id = 1
    cobject.mediaObject =  @media_object
    @media_object
  end

  def get_media_object(cobject, na)

    @media_object = cobject.mediaObject
    unless @media_object
      @media_object = Bookmark.new
    @media_object.name = na
    @media_object.typ_id = 1
    @media_object.save
    cobject.mediaObject =  @media_object
    cobject.save
    end
    @media_object
  end

  def getDirectory(d)
    a = []
    Find.find(d) {|path|
      if File.directory?(path)
      a << path
      end
    }
    a
  end

  def getFiles(d)
    a = []
    Find.find(d) {|path|
      unless File.directory?(path)
      a << path
      end
    }
    a
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :mediaObject, dependent: :destroy
  has_many :storageLocations
end

app/models/media_object.rb
class MediaObject < ActiveRecord::Base
  
  has_and_belongs_to_many   :attris
  #has_one :folder,   :foreign_key => "mediaObject_id", dependent: :destroy
  belongs_to :folder
  has_one :location, :foreign_key => "mediaObject_id", dependent: :destroy
  has_one :tag,      :foreign_key => "mediaObject_id", dependent: :destroy
  
  def filePath
    folder = Folder.find(folder_id)
    
  end
  
  def url
    folder = Folder.find(folder_id)
    a= folder.filePath + name
    a.gsub("\/", "\\")
  end
  
end

app/models/storage.rb
class Storage < ActiveRecord::Base
    has_many :storageLocations, dependent: :destroy
    has_many :folders, dependent: :destroy
  
  def filePath
    getSl.filePath.uri+"/"+path
  end

  def webPath
    getSl.webPath.name
  end

  def tnFilePath
    getSl.tnFilePath.name
  end

  def tnWebPath
    getSl.tnWebPath.name
  end

  private

  def getSl
    @sl ||= StorageLocation.where("storage_id = ? AND inUse = ?", id, true).first
  end

end

app/models/storage_location.rb
class StorageLocation < ActiveRecord::Base
  validates :storage_id, presence: true
  validates :filePath_id, presence: true
  validates :webPath_id, presence: true
  validates :tnFilePath_id, presence: true
  validates :tnWebPath_id, presence: true
  
  belongs_to :storage
  belongs_to :filePath, class_name: "Location"
  belongs_to :webPath,  class_name: "Location"
  belongs_to :tnFilePath, class_name: "Location"
  belongs_to :tnWebPath, class_name: "Location"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :mediaObject
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :ok }
        format.js {render 'media_objects/new_tag.jgs'}
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :ok }
    end
  end
end

app/helpers/agroups_helper.rb
module AgroupsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attris_helper.rb
module AttrisHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def new_tag(mo)
    # test code
    tag = Tag.new
    mo.tag = tag
  #
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>PMDB3</title>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id='menu'>
			Menue

			<%= link_to 'MO', media_objects_path%>
			<%= link_to 'Tags', tags_path%>
			<%= link_to 'Attributes', attris_path%>
			<%= link_to 'Locations', locations_path%>
			<%= link_to 'Storages', storages_path%>
			<%= link_to 'Storage Locations', storage_locations_path%>

		</div>

		<%= yield %>

	</body>
</html>

app/views/shared/_assign_attris.html.erb
<div class='attriAssign'>
<table>
  <tr>
    <th>Name</th>
    <th>Agroup</th>
    <th>Id sort</th>
    <th>Parent</th>
    <th>Keycode</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @attris = @media_object.attris
   @attris.each do |attri| %>
  <tr>
    <td><%= attri.name %></td>
    <td><%= attri.agroup_id %></td>
    <td><%= attri.id_sort %></td>
    <td><%= attri.parent_id %></td>
    <td><%= attri.keycode %></td>
    <td><%= attri.group_id %></td>
    <td><%= link_to 'Show', attri %></td>
    <td><%= link_to 'Edit', edit_attri_path(attri) %></td>
    <td><%= link_to 'Destroy', remove_attri_media_object_path(@media_object)+"?attri_id="+attri.id.to_s, confirm: 'Are you sure?', method: :delete%></td>
  </tr>
<% end %>
</table>

<% @attris = @media_object.attris
   @attris.each do |attri| %>
    <div class='attribute'> <%= attri.name %> 
    <%= link_to 'X', remove_attri_media_object_path(@media_object)+"?attri_id="+attri.id.to_s, confirm: 'Are you sure?', method: :delete, remote: true%>
  </div>
 <% end %>

<%= form_tag add_attri_media_object_path(@media_object), remote: true do%>
<%=text_field_tag :name, @attri_name, data: {autocomplete_source: autocomplete_attris_path}%>
<%= submit_tag "ADD"%>
<%if @newAttribute == true %>
<%=submit_tag "Create" %>
<%end%>

<% end%>


</div>

app/views/shared/_edit_tag.html.erb
<div class='editTag' draggable='true'>

<% @tag = @media_object.tag %>

<%if @tag%>

<%= form_for(@tag, remote: true) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%=link_to "Delete Notice", delete_tag_media_object_path(@media_object), remote: true %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%else%>
<%=link_to "New Notice", new_tag_media_object_path(@media_object), remote: true %>
<% end %>

</div>